# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jonathan Fager
title: IT-infrastrukturtekniker
email: jonathanjoelfager@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  jonathan-dnc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jofa1987
linkedin_username: jonathanfager
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About me
about_profile_image: images/1716268874476.jpg
about_content: | # this will include new lines to allow paragraphs
  Hej! Mitt namn är Jonathan och jag är nykläckt IT-infrastrukturstekniker. Förutom att hantera nätverk, moln och säkerhet inom IT har jag också intresse för automation (Ansible) samt programmering. 

  Det jag skulle säga jag är bäst på är: <mark>Lära mig snabbt</mark> och är <mark>Lojal</mark>
  
content:
  - title: Projekt # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Examensarbete - IT-automation i hybridmiljö
        link: github.com/jonathan-dnc/examensarbete
        # link_text: Project Website
        additional_links:
          - title:  Examensarbete
            icon: fab fa-github
            url: github.com/jonathan-dnc/examensarbete
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Om att implementera automation
        description: | # this will include new lines to allow paragraphs
          Jag skrev mitt examensarbete om att implementera automation i hybridmiljö. Anledningen? Jag tycker om automation och speciellt med <mark>Ansible</mark>. Det är någonting visst att få ett fullfjädrat skript att fungera. Genom arbetets gång lärde jag mig nya färdigheter och är stolt över resultatet!

  - title: Utbildning # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IRC Ljungby
        title: IT-infrastrukturtekniker - moln & säkerhet
        caption: Juli 2023 - Juni 2025
        sub_title: Yrkeshögskoleexamen
        link: https://www.ircyh.se/?page_id=490
        quote: >
          Yrkeshögskola i djupaste Småland som bedrivits sedan 1996. Med mycket tid förlagd för praktik garanteras erfarenhet.*
        description: | # this will include new lines to allow paragraphs
          Under min utbildning har jag fått lära mig mycket om relevant IT; allt från M365 till ISO/OSI-modellen. Under de båda åren som utbildningen pågick spenderades mycket tid på praktk vilket varit värdefullt. 

  - title: Yrkeserfarenhet # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Region Kronoberg
        link: https://www.regionkronoberg.se/
        # link_text: boringcompany.com
        sub_title: Vårdadministratör
        caption: November 2017 - Juli 2023
        quote: >
          Vårt uppdrag är att främja hälsa, hållbarhet och tillväxt i Kronoberg. Vår vision är ett gott liv i ett livskraftigt Kronoberg.*
        description: | # this will include new lines to allow paragraphs
            Arbete där jag var anställd som vårdadministratör och utförde allehanda administrativa arbetsuppgifter, fick också agera som de facto IT-tekniker bland kollegor.

  - title: Lite mer om mig!
    layout: text
    content: | # this will include new lines to allow paragraphs
      Förutom att syssla med IT och mitt hemmalabb så gillar jag:
      - Familjen, stolt bonuspappa.
      - Musik, spela och lyssna.
      - Husprojekt, för det måste man om man har ett hus.
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Referenser på begäran
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
